### ISSUE TITLE
[BUG] flutter 3.3.10, conduit 4.1.6, conduit db generate ERROR

### ISSUE THREAD

**Issue by PROGrand** [conduit-dart/conduit#168]
### Prerequisites
- Activated conduit 4.1.6.
- conduit create -t db conduit_app
```shell
flutter doctor -v
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22000.1455], locale ru-RU)
    • Flutter version 3.3.10 on channel stable at C:\Programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
```

### Error on migration generating:
```shell
conduit db generate
-- Conduit CLI Version: 4.1.6
-- Conduit project version: 4.1.6
*** Uncaught error
    IsolateSpawnException: Unable to spawn isolate: Error: Couldn't resolve the package 'conduit' in 'package:conduit/src/cli/migration_source.dart'.
```

**Comment by PROGrand** [comment]
### Workaround

Modify pubspec.yaml of generated project (add dependency `conduit: ^4.1.6`) and `pub get` before `conduit db generate`:

```yaml
name: conduit_app
description: An conduit application with a database connection, data model and OAuth 2.0 endpoints.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  conduit_core: ^4.0.0
  conduit: ^4.1.6

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.0.0
```

### Contribution target:
- [ ] add `conduit: ^4.1.6` dependency to project generator.
