### ISSUE TITLE
[proposal] deployment process in CLI conduit app

### ISSUE THREAD

**Issue by EhsanAramide** [conduit-dart/conduit#65]
Hi maintainers!

**This is a proposal and after agreement, I can implement it in framework**

I am a fan of CLI and Backend related Techs.  As I saw in the documentation conduit provides some templates for deploying with Docker and Kubernetes and I am interested to make deployment operations (like creating docker files, services, Kubernetes objects, configs) automate in a simple and interesting way which provides config of famous CI/CD platforms (like GitHub actions).

**Solution**
We can handle this by adding a command to the CLI app called `deploy` and after that, we can manage and configure files based on settings provided in `config.yaml`.

For example like below:
First of all we config the operations in `config.yaml`:
```yaml
# database setting and other ...
deploy:
  sdk_version: stable # version or channel
  platform: docker
  gen_env: .env # creates .env file spreatly for your env configs
  # by default .env contains database configs but you can add more like:
  env:
    - PAGINATION=15
    - HAS_CURL=true
```
After that, we start out operations
```sh
$ conduit deploy config # genrates deployment configs based on `config.yaml`
$ conduit deploy up # looks for associated files based on config and up the services
```
Generated docker file will be:
```dockerfile
FROM dart:stable
# this is app name in pubspec.yaml
WORKDIR /conduit_test_server
ADD . /conduit_test_server
EXPOSE 80
# and so on for other configurations
```
**Also, I can help you to manage and develop the framework CLI app and other parts, you can count on me guys! =))) I will be so happy to contribute with you on this great project!**
